locals  {
    resource_group_hub_name="${var.prefix}-hub"
    resource_group_spoke_name="${var.prefix}-spoke"
    vnet_hub_name="${var.prefix}-hub-vnet"
    vnet_spoke_name="${var.prefix}-spoke-vnet"
    vnet_hub_iprange="10.0.0.0/16"
    vnet_spoke_iprange="10.1.0.0/16"
    firewall_subnet="AzureFirewallSubnet"    
    vm_subnet="vm"
    firewall_subnet_iprange="10.0.0.0/24"
    vm_subnet_iprange="10.0.1.0/24"
    appgateway_subnet="appgateway"
    api_subnet="api"
    data_subnet="data"
    appgateway_subnet_iprange="10.1.0.0/24"
    api_subnet_iprange="10.1.1.0/24"
    data_subnet_iprange="10.1.2.0/24"
    hub_to_spoke_vnet_peer="${var.prefix}-hub-spoke-peer"
    spoke_to_hub_vnet_peer="${var.prefix}-spoke-hub-peer"
    firewall_publicip="${var.prefix}-fw-ip"
    firewall_name="${var.prefix}-fw"
    firewall_route_table_name="${var.prefix}fwrt"
    firewall_route_name="${var.prefix}fwrn"
    firewall_route_internet_name="${var.prefix}fwinternet"
    firewall_ipconfig_name="${var.prefix}fwconfig"
    appgateway_publicip="${var.prefix}-appgateway-ip"
    appgateway="${var.prefix}-appgateway"
    appgateway_probe="${var.prefix}-appgateway-probe"
    appgateway_private_ip_address="10.1.0.5"
    appgateway_frontend_ip_configuration_name="${var.prefix}-appgateway-fe-ip"
    appgateway_frontend_port_name="${var.prefix}-appgateway-fe-port"
    appgateway_listener_name="${var.prefix}-appgateway-listener"
    appgateway_http_setting_name="${var.prefix}-appgateway-http-setting"
    appgateway_backend_pool_name="${var.prefix}-appgateway-backend-pool"
    appgateway_ipconfig_name="${var.prefix}-appgateway-ipconfig"
    appgateway_request_routing_rule_name="${var.prefix}-appgateway-rule"


    # This needs to integrate with Steve
    apiapp="${var.prefix}-api"
}